### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/infografia-de-las-librerias-bg55-a#2]
[conceptos y funciones de una libreria y sus aplicaciones en las apps.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-bg55-a/files/8216873/conceptos.y.funciones.de.una.libreria.y.sus.aplicaciones.en.las.apps.pdf)

**Comment by JudithReynaCS** [comment]
Calificacion:18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
